//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.CTHoaDons = new HashSet<CTHoaDon>();
            this.DanhGias = new HashSet<DanhGia>();
        }
    
        public int MaHoaDon { get; set; }
        public System.DateTime NgayMua { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        [Required]
        [Display(Name = "Tên khách")]
        public string TenKhach { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        [Display(Name = "Số điện thoại")]
        public string SDT { get; set; }
        [Required]
        [Display(Name = "Địa chỉ")]
        public string DiaChi { get; set; }
        [Display(Name = "Hình thức thanh toán")]
        public Nullable<int> HinhThucThanhToan { get; set; }
        [Display(Name = "Hình thức giao hàng")]
        public Nullable<int> HinhThucGiaoHang { get; set; }
        public Nullable<int> MaNVDuyet { get; set; }
        [Display(Name = "Mã phiếu quà tặng")]
        public Nullable<int> MaPhieuQuaTang { get; set; }
        [Display(Name = "Số tiền giảm")]
        public Nullable<double> SoTienGiam { get; set; }
        [Display(Name = "Phí giao hàng")]
        public Nullable<int> PhiGiaoHang { get; set; }
        [Display(Name = "Tình trạng")]
        public Nullable<int> TinhTrang { get; set; }
        [Display(Name = "Tổng thanh toán")]
        public Nullable<double> TongThanhToan { get; set; }
        [Display(Name = "Ngày nhận")]
        public Nullable<System.DateTime> NgayNhan { get; set; }
        [Display(Name = "Ngày hủy đơn")]
        public Nullable<int> NguoiHuyDon { get; set; }
        [Display(Name = "Lý do hủy đơn")]
        public string LyDoHuy { get; set; }
        [Display(Name = "Lý do trả hàng")]
        public string LyDoTra { get; set; }
        public Nullable<System.DateTime> NgayHuyDon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHoaDon> CTHoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual PhieuQuaTang PhieuQuaTang { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
    }
}
