//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung_PhieuQuaTang
    {
        public long MaNguoiDung_PhieuQuaTang { get; set; }
        public Nullable<long> MaPhieuQuaTang { get; set; }
        public Nullable<long> MaNguoiDung { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual PhieuQuaTang PhieuQuaTang { get; set; }
    }
}
