//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuQuaTang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuQuaTang()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.NguoiDung_PhieuQuaTang = new HashSet<NguoiDung_PhieuQuaTang>();
        }
    
        public long MaPhieuQuaTang { get; set; }
        public string TenPhieuQuaTang { get; set; }
        public string MaGiamGia { get; set; }
        public int LoaiPhamVi { get; set; }
        public Nullable<double> GiaTri { get; set; }
        public Nullable<double> GiaTriDonHangToiThieu { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public System.DateTime NgayKichHoat { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public Nullable<int> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NguoiDung_PhieuQuaTang> NguoiDung_PhieuQuaTang { get; set; }
    }
}
