//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuQuaTang
    {
        public int MaPhieuQuaTang { get; set; }
        public Nullable<int> GiaTri { get; set; }
        public Nullable<int> TongSoLuong { get; set; }
        public Nullable<int> SoLuongConLai { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.DateTime NgayKichHoat { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> DiemThuongDoi { get; set; }
    }
}
