//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuQuaTang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuQuaTang()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int MaPhieuQuaTang { get; set; }
        public Nullable<int> GiaTri { get; set; }
        public Nullable<int> TongSoLuong { get; set; }
        public Nullable<int> SoLuongConLai { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public System.DateTime NgayKichHoat { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
