//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.CTHoaDons = new HashSet<CTHoaDon>();
            this.DanhGias = new HashSet<DanhGia>();
            this.Hinhs = new HashSet<Hinh>();
        }
    
        public int MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public int MaDanhMuc { get; set; }
        public string SeoTitle { get; set; }
        public int MaThuongHieu { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<int> SoLuongBan { get; set; }
        public Nullable<int> GiaBan { get; set; }
        public Nullable<int> GiaGiam { get; set; }
        public Nullable<int> DiemRate { get; set; }
        public Nullable<int> SoLuotRate { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public int BaoHanh { get; set; }
        public int MaLoaiCPU { get; set; }
        public string CPUInfo { get; set; }
        public string RAM { get; set; }
        public int MaLoaiGPU { get; set; }
        public string GPUInfo { get; set; }
        public int SizeManHinh { get; set; }
        public string ManHinh { get; set; }
        public string Pin { get; set; }
        public string LuuTru { get; set; }
        public Nullable<double> KhoiLuong { get; set; }
        public string Hinh { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayChinhSua { get; set; }
        public Nullable<bool> IsHide { get; set; }
    
        public virtual CPU CPU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHoaDon> CTHoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hinh> Hinhs { get; set; }
        public virtual LoaiGPU LoaiGPU { get; set; }
        public virtual ThuongHieu ThuongHieu { get; set; }
        public virtual SizeManHinh SizeManHinh1 { get; set; }
    }
}
