//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPhamNhapKho
    {
        public int MaSanPhamNhapKho { get; set; }
        public int MaSanPham { get; set; }
        [Display(Name = "Số lượng")]
        public Nullable<int> SoLuong { get; set; }
        [Display(Name = "Giá nhập")]
        public Nullable<double> GiaNhap { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
