//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.CTHoaDons = new HashSet<CTHoaDon>();
        }
    
        public int MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public int MaDanhMuc { get; set; }
        public int MaThuongHieu { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> GiaNhap { get; set; }
        public Nullable<int> GiaBan { get; set; }
        public Nullable<int> GiaGiam { get; set; }
        public Nullable<int> PhanTramGiamGia { get; set; }
        public int BaoHanh { get; set; }
        public int MaCPU { get; set; }
        public string RAM { get; set; }
        public int MaGPU { get; set; }
        public string ManHinh { get; set; }
        public string Hinh { get; set; }
        public System.DateTime NgayTao { get; set; }
        public Nullable<System.DateTime> NgayChinhSua { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsHide { get; set; }
    
        public virtual CPU CPU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHoaDon> CTHoaDons { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual GPU GPU { get; set; }
        public virtual ThuongHieu ThuongHieu { get; set; }
    }
}
