//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;
    using System.Web.Mvc;

    public partial class TinTuc
    {
        public TinTuc()
        {
            Thumbnail = "/Content/images/";
        }
        public int MaTinTuc { get; set; }
        public string TieuDe { get; set; }
        public string Thumbnail { get; set; }
        [AllowHtml]
        public string NoiDung { get; set; }
        public Nullable<int> MaSanPham { get; set; }
        public int MaNguoiTao { get; set; }
        public Nullable<int> MaNguoiSua { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayChinhSua { get; set; }
        public Nullable<bool> IsHide { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }
    }
}
